FROM osrf/ros:melodic-desktop-full
RUN apt update \
    && apt-get install -y ca-certificates gdb\
    && sed -i "s@http://.*archive.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list \
    && sed -i "s@http://.*security.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list \
    && apt-get clean \
    && apt-get update
RUN echo 'root:123456' |chpasswd \
    && apt update && apt install -y openssh-server \
	&& apt clean \
	&& rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp* \
	&& echo "PermitRootLogin yes" >> /etc/ssh/sshd_config \
    && echo "UsePAM no" >> /etc/ssh/sshd_config \
    && mkdir /var/run/sshd
RUN echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc 

EXPOSE 22
ENTRYPOINT ["/usr/sbin/sshd","-D"]
